flowchart TD
  0000_MAIN["0000-MAIN"]
  1000_PROCESS_INPUTS["1000-PROCESS-INPUTS"]
  1100_RECEIVE_MAP["1100-RECEIVE-MAP"]
  1200_EDIT_MAP_INPUTS["1200-EDIT-MAP-INPUTS"]
  1205_COMPARE_OLD_NEW["1205-COMPARE-OLD-NEW"]
  1210_EDIT_ACCOUNT["1210-EDIT-ACCOUNT"]
  1215_EDIT_MANDATORY["1215-EDIT-MANDATORY"]
  1220_EDIT_YESNO["1220-EDIT-YESNO"]
  1225_EDIT_ALPHA_REQD["1225-EDIT-ALPHA-REQD"]
  1230_EDIT_ALPHANUM_REQD["1230-EDIT-ALPHANUM-REQD"]
  1235_EDIT_ALPHA_OPT["1235-EDIT-ALPHA-OPT"]
  1240_EDIT_ALPHANUM_OPT["1240-EDIT-ALPHANUM-OPT"]
  1245_EDIT_NUM_REQD["1245-EDIT-NUM-REQD"]
  1250_EDIT_SIGNED_9V2["1250-EDIT-SIGNED-9V2"]
  1260_EDIT_US_PHONE_NUM["1260-EDIT-US-PHONE-NUM"]
  EDIT_AREA_CODE["EDIT-AREA-CODE"]
  EDIT_US_PHONE_PREFIX["EDIT-US-PHONE-PREFIX"]
  EDIT_US_PHONE_LINENUM["EDIT-US-PHONE-LINENUM"]
  1265_EDIT_US_SSN["1265-EDIT-US-SSN"]
  1270_EDIT_US_STATE_CD["1270-EDIT-US-STATE-CD"]
  1275_EDIT_FICO_SCORE["1275-EDIT-FICO-SCORE"]
  1280_EDIT_US_STATE_ZIP_CD["1280-EDIT-US-STATE-ZIP-CD"]
  2000_DECIDE_ACTION["2000-DECIDE-ACTION"]
  3000_SEND_MAP["3000-SEND-MAP"]
  3200_SETUP_SCREEN_VARS["3200-SETUP-SCREEN-VARS"]
  3300_SETUP_SCREEN_ATTRS["3300-SETUP-SCREEN-ATTRS"]
  9000_READ_ACCT["9000-READ-ACCT"]
  9500_STORE_FETCHED_DATA["9500-STORE-FETCHED-DATA"]
  9600_WRITE_PROCESSING["9600-WRITE-PROCESSING"]
  9700_CHECK_CHANGE_IN_REC["9700-CHECK-CHANGE-IN-REC"]
  COMMON_RETURN["COMMON-RETURN"]
  ABEND_ROUTINE["ABEND-ROUTINE"]
  0000_MAIN --> 1000_PROCESS_INPUTS
  0000_MAIN --> 2000_DECIDE_ACTION
  0000_MAIN --> 3000_SEND_MAP
  0000_MAIN --> 9000_READ_ACCT
  0000_MAIN --> 9600_WRITE_PROCESSING
  0000_MAIN --> COMMON_RETURN
  1000_PROCESS_INPUTS --> 1100_RECEIVE_MAP
  1000_PROCESS_INPUTS --> 1200_EDIT_MAP_INPUTS
  1200_EDIT_MAP_INPUTS --> 1210_EDIT_ACCOUNT
  1200_EDIT_MAP_INPUTS --> 1215_EDIT_MANDATORY
  1200_EDIT_MAP_INPUTS --> 1220_EDIT_YESNO
  1200_EDIT_MAP_INPUTS --> 1225_EDIT_ALPHA_REQD
  1200_EDIT_MAP_INPUTS --> 1230_EDIT_ALPHANUM_REQD
  1200_EDIT_MAP_INPUTS --> 1235_EDIT_ALPHA_OPT
  1200_EDIT_MAP_INPUTS --> 1240_EDIT_ALPHANUM_OPT
  1200_EDIT_MAP_INPUTS --> 1245_EDIT_NUM_REQD
  1200_EDIT_MAP_INPUTS --> 1250_EDIT_SIGNED_9V2
  1200_EDIT_MAP_INPUTS --> 1260_EDIT_US_PHONE_NUM
  1200_EDIT_MAP_INPUTS --> 1265_EDIT_US_SSN
  1200_EDIT_MAP_INPUTS --> 1270_EDIT_US_STATE_CD
  1200_EDIT_MAP_INPUTS --> 1275_EDIT_FICO_SCORE
  1200_EDIT_MAP_INPUTS --> 1280_EDIT_US_STATE_ZIP_CD
  1260_EDIT_US_PHONE_NUM --> EDIT_AREA_CODE
  1260_EDIT_US_PHONE_NUM --> EDIT_US_PHONE_PREFIX
  1260_EDIT_US_PHONE_NUM --> EDIT_US_PHONE_LINENUM
  3000_SEND_MAP -.-> 3100_SCREEN_INIT
  3000_SEND_MAP --> 3200_SETUP_SCREEN_VARS
  3000_SEND_MAP -.-> 3250_SETUP_INFOMSG
  3000_SEND_MAP --> 3300_SETUP_SCREEN_ATTRS
  3000_SEND_MAP -.-> 3400_SEND_SCREEN
  3200_SETUP_SCREEN_VARS -.-> 3201_SHOW_INITIAL_VALUES
  3200_SETUP_SCREEN_VARS -.-> 3202_SHOW_ORIGINAL_VALUES
  3200_SETUP_SCREEN_VARS -.-> 3203_SHOW_UPDATED_VALUES
  3300_SETUP_SCREEN_ATTRS -.-> 3310_PROTECT_ALL_ATTRS
  3300_SETUP_SCREEN_ATTRS -.-> 3320_UNPROTECT_FEW_ATTRS
  3300_SETUP_SCREEN_ATTRS -.-> 3390_SETUP_INFOMSG_ATTRS
  9000_READ_ACCT -.-> 9200_GETCARDXREF_BYACCT
  9000_READ_ACCT -.-> 9300_GETACCTDATA_BYACCT
  9000_READ_ACCT -.-> 9400_GETCUSTDATA_BYCUST
  9000_READ_ACCT --> 9500_STORE_FETCHED_DATA
  9600_WRITE_PROCESSING --> 9700_CHECK_CHANGE_IN_REC
