flowchart TD
  MAIN_PARA["MAIN-PARA"]
  1050_UPDATE_ACCOUNT["1050-UPDATE-ACCOUNT"]
  1200_GET_INTEREST_RATE["1200-GET-INTEREST-RATE"]
  1200_A_GET_DEFAULT_INT_RATE["1200-A-GET-DEFAULT-INT-RATE"]
  1300_COMPUTE_INTEREST["1300-COMPUTE-INTEREST"]
  1300_B_WRITE_TX["1300-B-WRITE-TX"]
  1400_COMPUTE_FEES["1400-COMPUTE-FEES"]
  1000_TCATBALF_GET_NEXT["1000-TCATBALF-GET-NEXT"]
  1100_GET_ACCT_DATA["1100-GET-ACCT-DATA"]
  1110_GET_XREF_DATA["1110-GET-XREF-DATA"]
  0000_TCATBALF_OPEN["0000-TCATBALF-OPEN"]
  0100_XREFFILE_OPEN["0100-XREFFILE-OPEN"]
  0200_DISCGRP_OPEN["0200-DISCGRP-OPEN"]
  0300_ACCTFILE_OPEN["0300-ACCTFILE-OPEN"]
  0400_TRANFILE_OPEN["0400-TRANFILE-OPEN"]
  9000_TCATBALF_CLOSE["9000-TCATBALF-CLOSE"]
  9100_XREFFILE_CLOSE["9100-XREFFILE-CLOSE"]
  9200_DISCGRP_CLOSE["9200-DISCGRP-CLOSE"]
  9300_ACCTFILE_CLOSE["9300-ACCTFILE-CLOSE"]
  9400_TRANFILE_CLOSE["9400-TRANFILE-CLOSE"]
  Z_GET_DB2_FORMAT_TIMESTAMP["Z-GET-DB2-FORMAT-TIMESTAMP"]
  9999_ABEND_PROGRAM["9999-ABEND-PROGRAM"]
  9910_DISPLAY_IO_STATUS["9910-DISPLAY-IO-STATUS"]
  MAIN_PARA --> 0000_TCATBALF_OPEN
  MAIN_PARA --> 0100_XREFFILE_OPEN
  MAIN_PARA --> 0200_DISCGRP_OPEN
  MAIN_PARA --> 0300_ACCTFILE_OPEN
  MAIN_PARA --> 0400_TRANFILE_OPEN
  MAIN_PARA --> 1000_TCATBALF_GET_NEXT
  MAIN_PARA --> 1050_UPDATE_ACCOUNT
  MAIN_PARA --> 1100_GET_ACCT_DATA
  MAIN_PARA --> 1110_GET_XREF_DATA
  MAIN_PARA --> 1200_GET_INTEREST_RATE
  MAIN_PARA --> 1300_COMPUTE_INTEREST
  MAIN_PARA --> 1400_COMPUTE_FEES
  MAIN_PARA --> 9000_TCATBALF_CLOSE
  MAIN_PARA --> 9100_XREFFILE_CLOSE
  MAIN_PARA --> 9200_DISCGRP_CLOSE
  MAIN_PARA --> 9300_ACCTFILE_CLOSE
  MAIN_PARA --> 9400_TRANFILE_CLOSE
  1050_UPDATE_ACCOUNT --> 9910_DISPLAY_IO_STATUS
  1050_UPDATE_ACCOUNT --> 9999_ABEND_PROGRAM
  1200_GET_INTEREST_RATE --> 9910_DISPLAY_IO_STATUS
  1200_GET_INTEREST_RATE --> 9999_ABEND_PROGRAM
  1200_GET_INTEREST_RATE --> 1200_A_GET_DEFAULT_INT_RATE
  1200_A_GET_DEFAULT_INT_RATE --> 9910_DISPLAY_IO_STATUS
  1200_A_GET_DEFAULT_INT_RATE --> 9999_ABEND_PROGRAM
  1300_COMPUTE_INTEREST --> 1300_B_WRITE_TX
  1300_B_WRITE_TX --> Z_GET_DB2_FORMAT_TIMESTAMP
  1300_B_WRITE_TX --> 9910_DISPLAY_IO_STATUS
  1300_B_WRITE_TX --> 9999_ABEND_PROGRAM
  1000_TCATBALF_GET_NEXT --> 9910_DISPLAY_IO_STATUS
  1000_TCATBALF_GET_NEXT --> 9999_ABEND_PROGRAM
  1100_GET_ACCT_DATA --> 9910_DISPLAY_IO_STATUS
  1100_GET_ACCT_DATA --> 9999_ABEND_PROGRAM
  1110_GET_XREF_DATA --> 9910_DISPLAY_IO_STATUS
  1110_GET_XREF_DATA --> 9999_ABEND_PROGRAM
  0000_TCATBALF_OPEN --> 9910_DISPLAY_IO_STATUS
  0000_TCATBALF_OPEN --> 9999_ABEND_PROGRAM
  0100_XREFFILE_OPEN --> 9910_DISPLAY_IO_STATUS
  0100_XREFFILE_OPEN --> 9999_ABEND_PROGRAM
  0200_DISCGRP_OPEN --> 9910_DISPLAY_IO_STATUS
  0200_DISCGRP_OPEN --> 9999_ABEND_PROGRAM
  0300_ACCTFILE_OPEN --> 9910_DISPLAY_IO_STATUS
  0300_ACCTFILE_OPEN --> 9999_ABEND_PROGRAM
  0400_TRANFILE_OPEN --> 9910_DISPLAY_IO_STATUS
  0400_TRANFILE_OPEN --> 9999_ABEND_PROGRAM
  9000_TCATBALF_CLOSE --> 9910_DISPLAY_IO_STATUS
  9000_TCATBALF_CLOSE --> 9999_ABEND_PROGRAM
  9100_XREFFILE_CLOSE --> 9910_DISPLAY_IO_STATUS
  9100_XREFFILE_CLOSE --> 9999_ABEND_PROGRAM
  9200_DISCGRP_CLOSE --> 9910_DISPLAY_IO_STATUS
  9200_DISCGRP_CLOSE --> 9999_ABEND_PROGRAM
  9300_ACCTFILE_CLOSE --> 9910_DISPLAY_IO_STATUS
  9300_ACCTFILE_CLOSE --> 9999_ABEND_PROGRAM
  9400_TRANFILE_CLOSE --> 9910_DISPLAY_IO_STATUS
  9400_TRANFILE_CLOSE --> 9999_ABEND_PROGRAM
  9999_ABEND_PROGRAM -.-> CEE3ABD
